### ISSUE TITLE
Rework defaults with profiles and easier command-line specification

### ISSUE THREAD

**Issue by DylanScottCarroll** [sizemore0125/skeletonkey#31]
This is a proposal of how to rework defaults to be more flexible and easier to deal with on the command line.

Part of this proposal is the concept of "profiles". The addition of profiles would absorb and expand upon the functionality of defaults. There would also be the option during `unlock` to override the default name for profiles, potentially making it `defaults` again.

In the most basic case, profiles can work exactly how defaults currently work:
``` yaml
profiles:
  - /path/to/config1
  - /path/to/config2
```
In this case, all of the values from the specified sub-configs are brought into the highest level of the main config just as they are with defaults. 

---

The first additional behavior that comes with this construct is the ability to specify multiple named profiles.
``` yaml
profiles:
  profile1:
    - /path/to/config1
    - /path/to/config2
  profile1:
    - /path/to/config3
    - /path/to/config4
```
In essence, this is just two different sets of defaults that can be switched between via the command line. The syntax for specifying profile on the command line would look something like `python main.py --profiles profile1` or potentially `python main.py profile1`.

This raises the question of which profile to select by default. It would be trivial to simply select the first profile specified sequentially, however, this may be somewhat opaque and not in line with the conceptualization of key-value maps as unordered. Alternatively, there could be a special profile called `default` or something similar which would be the same as other profiles except for the fact that it is the one selected when none are specified.

Additionally, the user will be able to specify configs on the command like to add to the set used. That might look something like `python main.py --profiles profile1 "/path/to/config4"`, in which case the values from the sub-config, onfig4, would be brought in on top of all of the sub-configs brought in from profile 1. 

---

Additionally, the user can optionally name the configs brought in from a given profile to enable easier overriding from the command line. Here is an example of what that may look like in an ML pipeline.
```yaml
profiles:
  train:
    model: train/model.yaml
    dataset: train/dataset.yaml
  debug:
    model: debug/model.yaml
    dataset: debug/dataset.yaml
```
In this case, the user could specify the mode to use while also bringing in individual components from the other mode.
`python main.py --profiles train debug.dataset`. Which would select the train profile, but also bring in the debug dataset sub-config.

It is possible that specifying in a sub-config with a given name from another profile would prevent that sub-config of the current profile with the same name from being brought in at all instead of just overriding its values. That behavior may be useful in some ways as there could be keys specified in, for example, `train/dataset.yaml` that aren't specified in `debug/dataset.yaml`. It would be polluting the config's namespace to include such values from the train dataset when the debug dataset is overwriting it. Those values would go unused or maybe even get in the way. However, this would require the user to maintain consistent naming between corresponding sub-configs in different profiles, and such correspondents might not be so simple in practice.

This behavior also potentially allows the user to treat the profiles as groups/folders of sub-configs rather than bespoke modes if that makes the workflow easier. For example, one could create profile called `models` in addition to `train` and `debug`. While, models would not be a sensible profile to specify by itself, one could use it to hold a list of easily addressable sub-configs. `python main.py --profiles train models.lstm` where the values from model.lstm override any model-related values specified by the train model. This demonstrates the ways in which this construction is conceptually flexible and can be thought of and used in various ways depending on the needs of the particular use case.

It is important to note that naming sub-configs does not stop a sub-config from being brought in by path.

---

It might also be possible to have lists of sub-configs as a named set in a profile. For example, one could place several config paths within `train.model` as a list, which would indicate that each of those sub-configs should be brought in when train.model is brought in.
Additionally, sub-profiles could allow more fine-grained control of combining aspects of profiles. Consider if the model key had two sub-keys, `backbone` and `head`. Each of these may have one or more sub-config paths specified. Whenever a profile is specified, all sub-configs from every sub-profile (and sub-sub-profile etc.) are also brought in. 
Here is an example that exhibits both of these potential behaviors
``` yaml
profiles:
  train:
    model:
      head: train/head.yaml
      backbone: train/backbone.yaml
    datasets:
      - train/dataset1.yaml
      - train/dataset2.yaml
  debug:
    model:
      head: debug/head.yaml
      backbone: debug/backbone.yaml
    datasets:
      - debug/dataset1.yaml
      - debug/dataset2.yaml
```

A command for such set of profiles might look like `python main.py --profiles train debug.model.head` which indicates that the training pipeline should be run, but that the model head should be the debug version. 

This sub-profile behavior may get somewhat complex. It is flexible and useful, but implementation and usage might have high cognitive load. In particular, should something like `debug.model.head` prevent the `train.model.head` from being brought in or just override the values it brings in? There may be unintentional name collisions in such complex cases that lead to more difficult-to-predict behavior.

---

Even assuming everything in this proposal is accepted, there are a number of questions to be answered.
1. Is `profiles` the best default keyword or is there some more sensible default?
2. Which should the syntax be for specifying a profile on the command line and/or should both options be possible.
3. How should the default profile be selected? Should it be the sequentially first profile or some specified default profile?
4. When specifying a named sub-config from another profile, how should that corresponding sub-config from the current profile be dealt with? Should it prevent the corresponding sub-config from inclusion entirely, or should it simply override its values as if it were specified afterwards.
5. Should sub-profiles be allowed or are the repercussions to complex?

**Comment by sizemore0125** [comment]
1. I think `profiles` is a sensible name for this feature.
2. I am ok with both options being available to the user. 
3. We maybe should have some way of specifying that a profile should be considered the default and included without specificaiton. We use the `?` and the `$` tags for flags and environemnt variables. Maybe we could use `!` for including a profile as a default when the yaml is parsed. 
4. If there is a key in the current profile that matches the key in another profile that you are specifying from the command-line, then whatever is last should overwrite. For example, `python pipeline.py train debug.model` should overwrite the `model` key in the train profile. Also, `python pipeline.py train debug.model train.model` should overwrite the debug overwrite. Also, `python pipeline.py train debug` should include all keys in train and overwrite all those keys with debug. Also, any keys in the main config should be overwitten by the addition of a profile. 
5. I am leaning towards subprofiles being allowed. But maybe we add that later.
